---
title: "**El Microbioma & La Salud Humana**"
author: "**Alejandro Navas González**"
date: today
thanks: "Andera Projekt"
format: 
  pdf:
    documentclass: report
    classoption: [twocolumn]
    highlight-style: breezedark
editor: source
warning: false
bibliography: archive.bib
link-citations: True
link-bibliography: True
---

## Introducción 

Las comunidades microbianas humanas o microbiomas existen en el cuerpo humano y dependen virtualmente de él para todas sus necesidades nutricionales y energéticas. Estos microbios muestran una diversidad genotípica extrema y constituyen algunas de las poblaciones más pequeñas, dinámicas y simbióticas conocidas. Los estudios de estos organismos, que están integralmente vinculados y sostenidos por el cuerpo humano, pueden proporcionar información útil sobre la salud humana y las enfermedades. Los tipos de macronutrientes requeridos y producidos por estas especies sin duda ayudarán a identificar objetivos moleculares clave que modulan la salud humana y la función digestiva.

## Comprender el Microbioma

El estudio de los microbios que viven en y dentro del cuerpo humano proporciona una gran visión de la genética de las poblaciones, las relaciones filogenéticas y los sistemas energéticos y metabólicos del cuerpo humano.[22] Podemos describir aún más el Microbioma como los genomas colectivos de poblaciones microbianas que incluyen bacterias, hongos, virus, bacteriófagos y protozoos, que viven dentro y en el cuerpo humano. Claramente, el microbioma contiene poblaciones muy grandes de organismos que viven en condiciones ambientales diferentes, a menudo extremas. Entonces, ¿cómo se puede describir y estudiar adecuadamente la genética de un Microbioma? ¿Y qué papel desempeñan las bacterias, hongos y protozoos en la salud y la homeostasis del huésped humano?

La importancia del microbioma en la salud humana solo se reconoció recientemente. Se cree que las comunidades de microbios desempeñan un papel importante en la regulación de la salud y las enfermedades humanas. El microbioma humano existe dentro de los compartimentos internos y en las superficies del cuerpo. Muchos organismos también se mueven libremente entre el cuerpo y las superficies con las que entran en contacto. La naturaleza dinámica del microbiota humana respalda un maquillaje genético de estos organismos que cambia y evoluciona rápidamente.[23]

El microbioma, aunque potencialmente patógeno, también ayuda a los humanos a realizar muchas funciones importantes que serían menos eficientes sin sus contribuciones, incluida la respuesta inmunitaria, la digestión adecuada y la regulación de la liberación y los niveles de péptidos y hormonas. Los microbios también digieren los alimentos para generar nutrientes para las células del huésped, sintetizan vitaminas, metabolizan medicamentos, detoxifican carcinógenos y estimulan la renovación de las células en el revestimiento del intestino.

## El microbiota intestinal

Se estima que el microbiota que habita en el intestino contiene más de 1000 organismos microbianos a nivel de especies.[24] Las bacterias se distribuyen a diferentes densidades a lo largo de la longitud del tracto gastrointestinal (TGI). La composición del microbiota intestinal puede diferir drásticamente entre las regiones del TGI, como la luz, el epitelio y la capa de moco.[25] Las interacciones importantes entre el intestino del huésped y sus habitantes microbianos siguen siendo esquivas debido a esa diversidad dramática y las marcadas diferencias en su distribución dentro del intestino.

La secuenciación de genomas microbianos del intestino proporciona información útil para la identificación de patógenos, cepas resistentes a antibióticos y poblaciones microbianas inmunomoduladoras.[25]

También se ha vinculado cambios en el microbiota intestinal con un comportamiento neurocognitivo deteriorado. Los ratones que recibieron el microbiota intestinal de ratones donantes que seguían una dieta alta en grasas o una dieta normal mostraron diferencias dramáticas en los resultados de salud. El microbiota intestinal de los ratones con una dieta alta en grasas se asoció con un aumento en la morbilidad, que se manifestó en cambios en los marcadores linfocíticos, la neuroinflamación y la función cerebrovascular comprometida.

## La salud intestinal y el cerebro

Los vínculos entre el microbioma intestinal y la salud humana siguen siendo en gran medida esquivos e inexplorados. La evidencia sugiere que las interacciones huésped-intestino están asociadas con una amplia gama de enfermedades y trastornos, como el asma, la diabetes, la obesidad, las alergias, el síndrome de intestino irritable y la enfermedad inflamatoria intestinal. Varios estudios epidemiológicos recientes proporcionan evidencia convincente del papel del microbioma intestinal en el desarrollo de trastornos del estado de ánimo y de ansiedad.[26] La heterogeneidad mantenida del microbioma intestinal parece ser importante para el funcionamiento normal del eje intestino-cerebro. El tracto gastrointestinal es el órgano endocrino más grande y diverso, y se cree que las interacciones entre los péptidos derivados del intestino y la modulación de la ansiedad relacionada con el estrés surgen de intercambios bidireccionales entre los péptidos del intestino que interactúan con receptores en células inmunitarias y células nerviosas. Estos péptidos modulan indirectamente el eje intestino-cerebro, influyendo en la síntesis de neurotransmisores, el grado de mielinización neuronal y otras vías reguladoras importantes para la reducción del estrés y la ansiedad.

El eje intestino-cerebro está implicado en la etiología de la ansiedad, respaldado por estudios en roedores en los que la colonización microbiana del intestino fue en gran parte eliminada mediante tratamiento con antibióticos.[27] Luego, el intestino se recolonizó en ratones receptores utilizando microbiota derivada del donante. Una muestra de donante se tomó de un animal con una dieta alta en grasas (HFD) y otra muestra de un animal alimentado con una dieta normal. Los ratones receptores fueron evaluados mediante secuenciación y clasificación taxonómica de los genomas microbianos y se evaluaron en cuanto a ansiedad, deterioro del comportamiento y pruebas neuropsiquiátricas.

La secuenciación de Illumina del 16S rRNA fue seguida por el procesamiento y la agrupación en OTUs. Las poblaciones microbianas intestinales de cada ratón receptor mostraron diferencias en composición y perfiles filogenéticos. Las pruebas conductuales evaluaron el comportamiento cognitivo, exploratorio y estereotipado. Las poblaciones microbióticas muestreadas se correlacionaron con los perfiles neuropsiquiátricos y respaldan la existencia de un eje intestino-cerebro que puede modular significativamente el estado de ánimo y la función conductual. A pesar de muchas incógnitas sobre los organismos que habitan el cuerpo humano, es evidente que la salud humana se ve influenciada de muchas maneras por el microbioma intestinal.


## Conclusiones

La metagenómica busca explorar y encontrar significado en los genomas de las comunidades microbianas ambientales. Estos grupos son microscópicos, simbióticos y dinámicos, y son importantes no solo para aprender sobre la estructura, función y organización ambiental, sino que también pueden proporcionar explicaciones para la prevalencia de enfermedades y la salud humana comprometida. Las poblaciones dramáticamente grandes de organismos dentro del microbioma humano proporcionan evidencia convincente de las relaciones entre la función molecular y fisiológica humana y las comunidades de organismos que viven en, sobre y alrededor de nosotros. Comprender las formas en que el huésped y el hábitat se influyen mutuamente requiere la construcción y caracterización de relaciones filogenéticas y determinar cómo los organismos, péptidos, información genética, ubicación, dieta y estilo de vida pueden afectar negativamente al microbioma intestinal y, en última instancia, la morbilidad y mortalidad humanas.

## Bibliografía