---
title: "**Proyecto SARS-CoV-2**"
author: "**Alejandro Navas González**"
date: today
thanks: "Andera Projekt"
format: 
  pdf:
    documentclass: report
    classoption: [twocolumn]
    highlight-style: breezedark
editor: source
warning: false
---

# **Objetivos del Proyecto**

**Genómica del SARS-CoV-2**

- Disponibilidad, recolección y compartición de datos
- Tipos de datos y cómo se generan/producen
- Recursos: Secuenciación de próxima generación (Next Generation Sequencing, NGS) de muestras virales

**Origen Zoonótico & Análisis de la Variación Genómica**

- Árboles filogenéticos - análisis evolutivo
- Similitud y variabilidad de secuencias nucleotídicas
- Mutación y recombinación

**Comparación con cepas existentes de Coronavirus**

- Árboles filogenéticos - análisis evolutivo
- Similitud y variabilidad de secuencias nucleotídicas

**Patogénesis del SARS-CoV-2**

- Patogénesis de la COVID-19: entrada y replicación celular
- Estructura genómica del SARS-COV-2: genes, proteínas estructurales y poliproteínas
- Proteína *Spike* y sus dominios funcionales
- Variación genómica y función de proteínas

**Elucidación de la firma transcriptómica para el medicamento Ruxolitinib**

- Resumen del medicamento Ruxolitinib
- Conjunto de datos transcriptómicos
- Análisis exploratorio de datos: análisis de componentes principales (PCA)
- Análisis de expresión génica diferencial
- Métodos de aprendizaje automático no supervisados: PCA y agrupamiento jerárquico (H-clust)
- Interpretación biológica de las firmas

